name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run Black (code formatter)
        run: black --check backend/

      - name: Run Flake8 (linter)
        run: flake8 backend/

      - name: Run Pytest (tests)
        run: pytest backend/
