name: Daily Poker Data Crawl (Selenium Enhanced)

on:
  schedule:
    # 매일 UTC 18:00 (한국시간 오전 3시)에 실행
    - cron: '0 18 * * *'
  workflow_dispatch: # 수동 실행 가능

# 최소 권한 원칙 적용
permissions:
  contents: read
  actions: write  # 아티팩트 업로드를 위한 권한

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Selenium 실행을 위한 더 긴 타임아웃
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          chromium-browser \
          chromium-chromedriver \
          xvfb \
          libxi6 \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libxrandr2 \
          libasound2 \
          libpangocairo-1.0-0 \
          libatk1.0-0 \
          libcairo-gobject2 \
          libgtk-3-0 \
          libgdk-pixbuf2.0-0
    
    - name: Install Python dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install fastapi firebase-admin cloudscraper beautifulsoup4 lxml requests google-auth google-auth-oauthlib google-auth-httplib2
        pip install undetected-chromedriver selenium
    
    - name: Create Firebase key from secret
      env:
        FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        mkdir -p backend/key
        echo "$FIREBASE_KEY" > backend/key/firebase-service-account-key.json
    
    - name: Run enhanced Selenium crawler
      env:
        GITHUB_ACTIONS: true
      run: |
        cd backend
        # 먼저 새로운 Selenium 크롤러 시도
        python selenium_crawler_advanced.py || {
          echo "Selenium 크롤러 실패, 기존 크롤러로 폴백..."
          python github_actions_crawler_firestore.py
        }
    
    - name: Upload error screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshots
        path: backend/error_screenshot_*.png
        retention-days: 7
    
    - name: Clean up
      if: always()
      run: |
        rm -rf backend/key
        rm -f backend/error_screenshot_*.png