name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: List files for debugging
        run: ls -R

      - name: Install dependencies
        run: npm install --prefix ./frontend

      - name: Run tests
        run: npm test --prefix ./frontend

      - name: Build project
        run: npm run build --prefix ./frontend
