name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "DEBUG: Show directory structure"
        run: ls -R

      - name: Install dependencies
        working-directory: ./poker-online-analyze/frontend
        run: npm install

      - name: Run tests
        working-directory: ./poker-online-analyze/frontend
        run: npm test

      - name: Build project
        working-directory: ./poker-online-analyze/frontend
        run: npm run build
